/*
 * File:           EngineHandler.java
 * Date:           12. August 2007  21:35
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
package org.railsim.xml;

import org.xml.sax.*;

public interface EngineHandler {

	/**
	 *
	 * A container element start event handling method.
	 *
	 * @param meta attributes
	 * @throws SAXException
	 */
	public void start_engine(final Attributes meta) throws SAXException;

	/**
	 *
	 * A container element end event handling method.
	 *
	 * @throws SAXException
	 */
	public void end_engine() throws SAXException;

	/**
	 *
	 * An empty element event handling method.
	 *
	 * @param meta
	 * @throws SAXException
	 */
	public void handle_power(final Attributes meta) throws SAXException;
}
