/*
 * File:           GamestoreParser.java
 * Date:           27. September 2007  17:31
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           26. September 2007  10:20
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           26. September 2007  09:15
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           25. September 2007  13:17
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           25. September 2007  13:05
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           19. September 2007  11:16
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           28. Juli 2007  20:34
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           18. Juli 2007  14:20
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           18. Juli 2007  08:11
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           2. Juli 2007  08:15
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           21. Mai 2007  14:34
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           17. Mai 2007  00:51
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           GamestoreParser.java
 * Date:           16. Mai 2007  19:15
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
package org.railsim.xml;

import org.xml.sax.*;

/**
 *
 * The class reads XML documents according to specified DTD and
 * translates all related events into GamestoreHandler events.
 * <p>Usage sample:
 * <pre>
 *    GamestoreParser parser = new GamestoreParser(...);
 *    parser.parse(new InputSource("..."));
 * </pre>
 * <p><b>Warning:</b> the class is machine generated. DO NOT MODIFY</p>
 */
public class GamestoreParser implements ContentHandler {

	private java.lang.StringBuffer buffer;
	private GamestoreHandler handler;
	private java.util.Stack context;
	private EntityResolver resolver;

	/**
	 *
	 * Creates a parser instance.
	 *
	 * @param handler handler interface implementation (never <code>null</code>
	 * @param resolver SAX entity resolver implementation or <code>null</code>.
	 * It is recommended that it could be able to resolve at least the DTD.
	 */
	public GamestoreParser(final GamestoreHandler handler, final EntityResolver resolver) {
		this.handler = handler;
		this.resolver = resolver;
		buffer = new StringBuffer(111);
		context = new java.util.Stack();
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void setDocumentLocator(Locator locator) {
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void startDocument() throws SAXException {
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void endDocument() throws SAXException {
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void startElement(java.lang.String ns, java.lang.String name, java.lang.String qname, Attributes attrs) throws SAXException {
		dispatch(true);
		context.push(new Object[]{
					qname, new org.xml.sax.helpers.AttributesImpl(attrs)
				});
		switch (qname) {
			case "connect":
				handler.handle_connect(attrs);
				break;
			case "data":
				handler.handle_data(attrs);
				break;
			case "pathelement":
				handler.handle_pathelement(attrs);
				break;
			case "epart":
				handler.handle_epart(attrs);
				break;
			case "tpart":
				handler.start_tpart(attrs);
				break;
			case "time":
				handler.handle_time(attrs);
				break;
			case "trackobject":
				handler.start_trackobject(attrs);
				break;
			case "pathrequest":
				handler.start_pathrequest(attrs);
				break;
			case "path":
				handler.start_path(attrs);
				break;
			case "command":
				handler.start_command(attrs);
				break;
			case "train":
				handler.start_train(attrs);
				break;
			case "frequence":
				handler.handle_frequence(attrs);
				break;
			case "trains":
				handler.start_trains(attrs);
				break;
			case "savegame":
				handler.start_savegame(attrs);
				break;
			case "emit":
				handler.start_emit(attrs);
				break;
			case "track":
				handler.start_track(attrs);
				break;
			case "tracks":
				handler.start_tracks(attrs);
				break;
			case "pathroute":
				handler.start_pathroute(attrs);
				break;
			case "signaldata":
				handler.start_signaldata(attrs);
				break;
			case "pathqueue":
				handler.start_pathqueue(attrs);
				break;
			case "mutex":
				handler.handle_mutex(attrs);
				break;
			case "point":
				handler.handle_point(attrs);
				break;
			case "startqueue":
				handler.start_startqueue(attrs);
				break;
			case "routes":
				handler.start_routes(attrs);
				break;
			case "route":
				handler.start_route(attrs);
				break;
			case "requestedpath":
				handler.handle_requestedpath(attrs);
				break;
			case "trainemitter":
				handler.start_trainemitter(attrs);
				break;
		}
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void endElement(java.lang.String ns, java.lang.String name, java.lang.String qname) throws SAXException {
		dispatch(false);
		context.pop();
		switch (qname) {
			case "tpart":
				handler.end_tpart();
				break;
			case "trackobject":
				handler.end_trackobject();
				break;
			case "pathrequest":
				handler.end_pathrequest();
				break;
			case "path":
				handler.end_path();
				break;
			case "command":
				handler.end_command();
				break;
			case "train":
				handler.end_train();
				break;
			case "trains":
				handler.end_trains();
				break;
			case "savegame":
				handler.end_savegame();
				break;
			case "emit":
				handler.end_emit();
				break;
			case "track":
				handler.end_track();
				break;
			case "tracks":
				handler.end_tracks();
				break;
			case "pathroute":
				handler.end_pathroute();
				break;
			case "signaldata":
				handler.end_signaldata();
				break;
			case "pathqueue":
				handler.end_pathqueue();
				break;
			case "startqueue":
				handler.end_startqueue();
				break;
			case "routes":
				handler.end_routes();
				break;
			case "route":
				handler.end_route();
				break;
			case "trainemitter":
				handler.end_trainemitter();
				break;
		}
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void characters(char[] chars, int start, int len) throws SAXException {
		buffer.append(chars, start, len);
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void ignorableWhitespace(char[] chars, int start, int len) throws SAXException {
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void processingInstruction(java.lang.String target, java.lang.String data) throws SAXException {
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void startPrefixMapping(final java.lang.String prefix, final java.lang.String uri) throws SAXException {
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void endPrefixMapping(final java.lang.String prefix) throws SAXException {
	}

	/**
	 *
	 * This SAX interface method is implemented by the parser.
	 */
	@Override
	public final void skippedEntity(java.lang.String name) throws SAXException {
	}

	private void dispatch(final boolean fireOnlyIfMixed) throws SAXException {
		if (fireOnlyIfMixed && buffer.length() == 0) {
			return; //skip it
		}
		Object[] ctx = (Object[]) context.peek();
		String here = (String) ctx[0];
		Attributes attrs = (Attributes) ctx[1];
		if ("tdata".equals(here)) {
			if (fireOnlyIfMixed) {
				throw new IllegalStateException("Unexpected characters() event! (Missing DTD?)");
			}
			handler.handle_tdata(buffer.length() == 0 ? null : buffer.toString(), attrs);
		} else {
			//do not care
		}
		buffer.delete(0, buffer.length());
	}

	/**
	 *
	 * The recognizer entry method taking an InputSource.
	 *
	 * @param input InputSource to be parsed.
	 * @throws java.io.IOException on I/O error.
	 * @throws SAXException propagated exception thrown by a DocumentHandler.
	 * @throws javax.xml.parsers.ParserConfigurationException a parser satisfining requested configuration can not be created.
	 * @throws javax.xml.parsers.FactoryConfigurationRrror if the implementation can not be instantiated.
	 */
	public void parse(final InputSource input) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
		parse(input, this);
	}

	/**
	 *
	 * The recognizer entry method taking a URL.
	 *
	 * @param url URL source to be parsed.
	 * @throws java.io.IOException on I/O error.
	 * @throws SAXException propagated exception thrown by a DocumentHandler.
	 * @throws javax.xml.parsers.ParserConfigurationException a parser satisfining requested configuration can not be created.
	 * @throws javax.xml.parsers.FactoryConfigurationRrror if the implementation can not be instantiated.
	 */
	public void parse(final java.net.URL url) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
		parse(new InputSource(url.toExternalForm()), this);
	}

	/**
	 *
	 * The recognizer entry method taking an Inputsource.
	 *
	 * @param input InputSource to be parsed.
	 * @throws java.io.IOException on I/O error.
	 * @throws SAXException propagated exception thrown by a DocumentHandler.
	 * @throws javax.xml.parsers.ParserConfigurationException a parser satisfining requested configuration can not be created.
	 * @throws javax.xml.parsers.FactoryConfigurationRrror if the implementation can not be instantiated.
	 */
	public static void parse(final InputSource input, final GamestoreHandler handler) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
		parse(input, new GamestoreParser(handler, null));
	}

	/**
	 *
	 * The recognizer entry method taking a URL.
	 *
	 * @param url URL source to be parsed.
	 * @throws java.io.IOException on I/O error.
	 * @throws SAXException propagated exception thrown by a DocumentHandler.
	 * @throws javax.xml.parsers.ParserConfigurationException a parser satisfining requested configuration can not be created.
	 * @throws javax.xml.parsers.FactoryConfigurationRrror if the implementation can not be instantiated.
	 */
	public static void parse(final java.net.URL url, final GamestoreHandler handler) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
		parse(new InputSource(url.toExternalForm()), handler);
	}

	private static void parse(final InputSource input, final GamestoreParser recognizer) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
		javax.xml.parsers.SAXParserFactory factory = javax.xml.parsers.SAXParserFactory.newInstance();
		factory.setValidating(false);  //the code was generated according DTD
		factory.setNamespaceAware(false);  //the code was generated according DTD
		XMLReader parser = factory.newSAXParser().getXMLReader();
		parser.setContentHandler(recognizer);
		parser.setErrorHandler(recognizer.getDefaultErrorHandler());
		if (recognizer.resolver != null) {
			parser.setEntityResolver(recognizer.resolver);
		}
		parser.parse(input);
	}

	/**
	 *
	 * Creates default error handler used by this parser.
	 *
	 * @return org.xml.sax.ErrorHandler implementation
	 */
	protected ErrorHandler getDefaultErrorHandler() {
		return new ErrorHandler() {
			@Override
			public void error(SAXParseException ex) throws SAXException {
				if (context.isEmpty()) {
					System.err.println("Missing DOCTYPE.");
				}
				throw ex;
			}

			@Override
			public void fatalError(SAXParseException ex) throws SAXException {
				throw ex;
			}

			@Override
			public void warning(SAXParseException ex) throws SAXException {
				// ignore
			}
		};

	}
}
