/*
 * File:           RollingstockHandler.java
 * Date:           7. September 2007  13:14
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
/*
 * File:           RollingstockHandler.java
 * Date:           12. August 2007  21:53
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
package org.railsim.xml;

import org.xml.sax.*;

public interface RollingstockHandler {

	/**
	 *
	 * A container element start event handling method.
	 *
	 * @param meta attributes
	 */
	public void start_rollingstock(final Attributes meta) throws SAXException;

	/**
	 *
	 * A container element end event handling method.
	 */
	public void end_rollingstock() throws SAXException;

	/**
	 *
	 * An empty element event handling method.
	 *
	 * @param data value or null
	 */
	public void handle_appearance(final Attributes meta) throws SAXException;

	/**
	 *
	 * An empty element event handling method.
	 *
	 * @param data value or null
	 */
	public void handle_weight(final Attributes meta) throws SAXException;

	/**
	 *
	 * An empty element event handling method.
	 *
	 * @param data value or null
	 */
	public void handle_measure(final Attributes meta) throws SAXException;

	/**
	 *
	 * A data element event handling method.
	 *
	 * @param data value or null
	 * @param meta attributes
	 */
	public void handle_drawappearance(final java.lang.String data, final Attributes meta) throws SAXException;

	/**
	 *
	 * An empty element event handling method.
	 *
	 * @param data value or null
	 */
	public void handle_engine(final Attributes meta) throws SAXException;

	/**
	 *
	 * An empty element event handling method.
	 *
	 * @param data value or null
	 */
	public void handle_speed(final Attributes meta) throws SAXException;

	/**
	 *
	 * An empty element event handling method.
	 *
	 * @param data value or null
	 */
	public void handle_coupling(final Attributes meta) throws SAXException;

	/**
	 *
	 * An empty element event handling method.
	 *
	 * @param data value or null
	 */
	public void handle_type(final Attributes meta) throws SAXException;
}
