/*
 * File:           TrainsetsHandler.java
 * Date:           12. August 2007  22:15
 *
 * @author  js
 * @version generated by NetBeans XML module
 */
package org.railsim.xml;

import org.xml.sax.*;

public interface TrainsetsHandler {

	/**
	 *
	 * A container element start event handling method.
	 *
	 * @param meta attributes
	 */
	public void start_trainsets(final Attributes meta) throws SAXException;

	/**
	 *
	 * A container element end event handling method.
	 */
	public void end_trainsets() throws SAXException;

	/**
	 *
	 * An empty element event handling method.
	 *
	 * @param data value or null
	 */
	public void handle_stock(final Attributes meta) throws SAXException;

	/**
	 *
	 * A container element start event handling method.
	 *
	 * @param meta attributes
	 */
	public void start_set(final Attributes meta) throws SAXException;

	/**
	 *
	 * A container element end event handling method.
	 */
	public void end_set() throws SAXException;
}
