/*
 * $Revision: 20 $
 * Copyright 2008 js-home.org
 * $Name: not supported by cvs2svn $
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.railsim.gui.panels;

import java.text.*;

import javax.swing.*;
import javax.swing.JFormattedTextField.AbstractFormatter;

import org.railsim.*;
import org.railsim.editor.EditorActionEvent;
import org.railsim.editor.EditorEvent;
import org.railsim.event.*;
import org.railsim.service.track;

/**
 *
 * @author js
 */
public class mainpanel_edittrack extends javax.swing.JPanel {

	private class FormattedTextFieldVerifier extends InputVerifier {

		@Override
		public boolean verify(JComponent input) {
			if (input instanceof JFormattedTextField) {
				JFormattedTextField ftf = (JFormattedTextField) input;
				AbstractFormatter formatter = ftf.getFormatter();
				if (formatter != null) {
					String text = ftf.getText();
					try {
						formatter.stringToValue(text);
						return true;
					} catch (ParseException pe) {
						return false;
					}
				}
			}
			return true;
		}

		@Override
		public boolean shouldYieldFocus(JComponent input) {
			return verify(input);
		}
	};
	track workingTrack = null;

	/**
	 * Creates new form mainpanel_file
	 */
	public mainpanel_edittrack() {
		initComponents();
		dataCollector.collector.editorEventListeners.addListener(new AbstractListener() {
			@Override
			public void action(AbstractEvent e) {
				trackEvent((EditorEvent) e);
			}
		});
		level_Slider.setMinimum(track.MINLEVEL);
		level_Slider.setMaximum(track.MAXLEVEL);
		level_Slider.setValue(0);
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        editMode = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        editModePanel = new javax.swing.JPanel();
        edit_RadioButton = new javax.swing.JRadioButton();
        addedit_RadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        add_Button = new javax.swing.JButton();
        del_Button = new javax.swing.JButton();
        copy_Button = new javax.swing.JButton();
        junction_Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        level_Slider = new javax.swing.JSlider();
        level_Label = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setLabelFor(editModePanel);
        jLabel1.setText("Editor Modus");
        add(jLabel1);

        editModePanel.setLayout(new javax.swing.BoxLayout(editModePanel, javax.swing.BoxLayout.PAGE_AXIS));

        editMode.add(edit_RadioButton);
        edit_RadioButton.setText("bearbeiten");
        edit_RadioButton.setToolTipText("neues Gleis nur \u00fcber den \"Neues Gleis\" Knopf");
        edit_RadioButton.setActionCommand("edit-only");
        edit_RadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        edit_RadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        edit_RadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        editModePanel.add(edit_RadioButton);

        editMode.add(addedit_RadioButton);
        addedit_RadioButton.setSelected(true);
        addedit_RadioButton.setText("neu & bearbeiten");
        addedit_RadioButton.setToolTipText("neues Gleis durch klicken in einen leeren Bereich");
        addedit_RadioButton.setActionCommand("add+edit");
        addedit_RadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addedit_RadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addedit_RadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        editModePanel.add(addedit_RadioButton);

        add(editModePanel);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator1.setMinimumSize(new java.awt.Dimension(5, 25));
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 25));
        add(jSeparator1);

        add_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org//railsim/gui/resources/add.png")));
        add_Button.setText("New Track");
        add_Button.setActionCommand("new track");
        add_Button.setEnabled(false);
        add_Button.setMargin(new java.awt.Insets(2, 5, 2, 5));
        add_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        add(add_Button);

        del_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/delete.png")));
        del_Button.setText("Delete");
        del_Button.setActionCommand("del");
        del_Button.setEnabled(false);
        del_Button.setMargin(new java.awt.Insets(2, 5, 2, 5));
        del_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        add(del_Button);

        copy_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/clone.png")));
        copy_Button.setText("Append");
        copy_Button.setActionCommand("append");
        copy_Button.setEnabled(false);
        copy_Button.setMargin(new java.awt.Insets(2, 5, 2, 5));
        copy_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        add(copy_Button);

        junction_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/junction.png")));
        junction_Button.setText("Junction");
        junction_Button.setActionCommand("junction");
        junction_Button.setEnabled(false);
        junction_Button.setMargin(new java.awt.Insets(2, 5, 2, 5));
        junction_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        add(junction_Button);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        level_Slider.setMajorTickSpacing(1);
        level_Slider.setMaximum(10);
        level_Slider.setMinorTickSpacing(1);
        level_Slider.setSnapToTicks(true);
        level_Slider.setToolTipText("H\u00f6he");
        level_Slider.setValue(0);
        level_Slider.setPreferredSize(new java.awt.Dimension(100, 24));
        level_Slider.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                level_SliderStateChanged(evt);
            }
        });

        jPanel1.add(level_Slider);

        level_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        level_Label.setLabelFor(level_Slider);
        level_Label.setMaximumSize(new java.awt.Dimension(40, 24));
        level_Label.setMinimumSize(new java.awt.Dimension(20, 10));
        level_Label.setPreferredSize(new java.awt.Dimension(20, 23));
        jPanel1.add(level_Label);

        add(jPanel1);

    }// </editor-fold>//GEN-END:initComponents

    private void level_SliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_level_SliderStateChanged
    {//GEN-HEADEREND:event_level_SliderStateChanged
		level_Label.setText("" + level_Slider.getValue());
		dataCollector.collector.thegame.runAction(new EditorActionEvent<>("level", level_Slider.getValue()));
    }//GEN-LAST:event_level_SliderStateChanged

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonActionPerformed
    {//GEN-HEADEREND:event_ButtonActionPerformed
		dataCollector.collector.thegame.runAction(new EditorActionEvent(evt.getActionCommand()));
		add_Button.setEnabled(edit_RadioButton.isSelected());
    }//GEN-LAST:event_ButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_Button;
    private javax.swing.JRadioButton addedit_RadioButton;
    private javax.swing.JButton copy_Button;
    private javax.swing.JButton del_Button;
    private javax.swing.ButtonGroup editMode;
    private javax.swing.JPanel editModePanel;
    private javax.swing.JRadioButton edit_RadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton junction_Button;
    private javax.swing.JLabel level_Label;
    private javax.swing.JSlider level_Slider;
    // End of variables declaration//GEN-END:variables

	void trackEvent(EditorEvent e) {
		workingTrack = e.getTrack();
		switch (e.getType()) {
			case EditorEvent.TRACK_SELECTED:
			case EditorEvent.TRACK_VALUE_CHANGED:
				if (workingTrack.isUsed()) {
					del_Button.setEnabled(false);
				} else {
					del_Button.setEnabled(true);
				}
				if (workingTrack.isEndFree()) {
					copy_Button.setEnabled(true);
				} else {
					copy_Button.setEnabled(false);
				}
				if (workingTrack.getNext(0) != null) {
					junction_Button.setEnabled(true);
				} else {
					junction_Button.setEnabled(false);
				}
				level_Slider.setValue(workingTrack.getLevel());
			// continue case, no break
			case EditorEvent.TRACK_MOVED:
				break;
			case EditorEvent.TRACK_UNSELECTED:
				del_Button.setEnabled(false);
				copy_Button.setEnabled(false);
				junction_Button.setEnabled(false);
				break;
		}
	}
}
