/*
 * $Revision: 20 $
 * Copyright 2008 js-home.org
 * $Name: not supported by cvs2svn $
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.railsim.gui.panels;

import org.railsim.*;
import org.railsim.event.*;

/**
 *
 * @author js
 */
public class mainpanel_test extends javax.swing.JPanel {

	/**
	 * Creates new form hidepanel_file
	 */
	public mainpanel_test() {
		initComponents();

		dataCollector.collector.filenameListeners.addListener(new AbstractListener() {
			@Override
			public void action(AbstractEvent e) {
				filename_TextField.setText(dataCollector.collector.getFilename());
			}
		});
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        filename_TextField = new javax.swing.JTextField();
        setfilename_Button = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        filename_TextField.setMinimumSize(new java.awt.Dimension(80, 20));
        filename_TextField.setPreferredSize(new java.awt.Dimension(80, 20));
        add(filename_TextField);

        setfilename_Button.setText("set");
        setfilename_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                setfilename_ButtonActionPerformed(evt);
            }
        });

        add(setfilename_Button);

    }// </editor-fold>//GEN-END:initComponents

    private void setfilename_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_setfilename_ButtonActionPerformed
    {//GEN-HEADEREND:event_setfilename_ButtonActionPerformed
		dataCollector.collector.setFilename(filename_TextField.getText());
    }//GEN-LAST:event_setfilename_ButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filename_TextField;
    private javax.swing.JButton setfilename_Button;
    // End of variables declaration//GEN-END:variables
}
