/*
 * $Revision: 20 $
 * Copyright 2008 js-home.org
 * $Name: not supported by cvs2svn $
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.railsim.gui.panels;

import java.text.*;

import javax.swing.*;
import javax.swing.JFormattedTextField.AbstractFormatter;

import org.railsim.*;
import org.railsim.editor.EditorActionEvent;
import org.railsim.editor.EditorEvent;
import org.railsim.event.*;
import org.railsim.service.track;
import org.railsim.service.trackGroup;

/**
 *
 * @author js
 */
public class mainpanel_edittrackgroup extends javax.swing.JPanel {

	private class FormattedTextFieldVerifier extends InputVerifier {

		@Override
		public boolean verify(JComponent input) {
			if (input instanceof JFormattedTextField) {
				JFormattedTextField ftf = (JFormattedTextField) input;
				AbstractFormatter formatter = ftf.getFormatter();
				if (formatter != null) {
					String text = ftf.getText();
					try {
						formatter.stringToValue(text);
						return true;
					} catch (ParseException pe) {
						return false;
					}
				}
			}
			return true;
		}

		@Override
		public boolean shouldYieldFocus(JComponent input) {
			return verify(input);
		}
	};
	trackGroup workingTrack = null;

	/**
	 * Creates new form mainpanel_file
	 */
	public mainpanel_edittrackgroup() {
		initComponents();
		dataCollector.collector.editorEventListeners.addListener(new AbstractListener() {
			@Override
			public void action(AbstractEvent e) {
				trackEvent((EditorEvent) e);
			}
		});
		level_Slider.setMinimum(track.MINLEVEL);
		level_Slider.setMaximum(track.MAXLEVEL);
		level_Slider.setValue(0);
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        clone_Button = new javax.swing.JButton();
        del_Button = new javax.swing.JButton();
        clearMark_Button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        level_Slider = new javax.swing.JSlider();
        level_Label = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        touchedT_CB = new javax.swing.JCheckBox();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        clone_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/cp_paste.png")));
        clone_Button.setText("Duplicate");
        clone_Button.setActionCommand("clone");
        clone_Button.setEnabled(false);
        clone_Button.setMargin(new java.awt.Insets(2, 5, 2, 5));
        clone_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        add(clone_Button);

        del_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/delete.png")));
        del_Button.setText("Delete");
        del_Button.setActionCommand("del");
        del_Button.setEnabled(false);
        del_Button.setMargin(new java.awt.Insets(2, 5, 2, 5));
        del_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        add(del_Button);

        clearMark_Button.setText("Clear Section");
        clearMark_Button.setActionCommand("clearselection");
        clearMark_Button.setEnabled(false);
        clearMark_Button.setMargin(new java.awt.Insets(2, 5, 2, 5));
        clearMark_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        add(clearMark_Button);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator1.setMinimumSize(new java.awt.Dimension(5, 25));
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 25));
        add(jSeparator1);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        level_Slider.setMajorTickSpacing(1);
        level_Slider.setMaximum(10);
        level_Slider.setMinorTickSpacing(1);
        level_Slider.setSnapToTicks(true);
        level_Slider.setToolTipText("H\u00f6he");
        level_Slider.setValue(0);
        level_Slider.setPreferredSize(new java.awt.Dimension(100, 24));
        level_Slider.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                level_SliderStateChanged(evt);
            }
        });

        jPanel1.add(level_Slider);

        level_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        level_Label.setLabelFor(level_Slider);
        level_Label.setMaximumSize(new java.awt.Dimension(40, 24));
        level_Label.setMinimumSize(new java.awt.Dimension(20, 10));
        level_Label.setPreferredSize(new java.awt.Dimension(20, 23));
        jPanel1.add(level_Label);

        add(jPanel1);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMaximumSize(new java.awt.Dimension(5, 32767));
        jSeparator2.setMinimumSize(new java.awt.Dimension(5, 25));
        jSeparator2.setPreferredSize(new java.awt.Dimension(5, 25));
        add(jSeparator2);

        touchedT_CB.setText("auch Teilgleise");
        touchedT_CB.setActionCommand("touchedT");
        touchedT_CB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        touchedT_CB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        touchedT_CB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CBActionPerformed(evt);
            }
        });

        add(touchedT_CB);

    }// </editor-fold>//GEN-END:initComponents

    private void CBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CBActionPerformed
    {//GEN-HEADEREND:event_CBActionPerformed
		dataCollector.collector.thegame.runAction(new EditorActionEvent(evt.getActionCommand(), ((JCheckBox) evt.getSource()).isSelected()));
    }//GEN-LAST:event_CBActionPerformed

    private void level_SliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_level_SliderStateChanged
    {//GEN-HEADEREND:event_level_SliderStateChanged
		level_Label.setText("" + level_Slider.getValue());
		dataCollector.collector.thegame.runAction(new EditorActionEvent<>("level", level_Slider.getValue()));
    }//GEN-LAST:event_level_SliderStateChanged

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonActionPerformed
    {//GEN-HEADEREND:event_ButtonActionPerformed
		dataCollector.collector.thegame.runAction(new EditorActionEvent(evt.getActionCommand()));
    }//GEN-LAST:event_ButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearMark_Button;
    private javax.swing.JButton clone_Button;
    private javax.swing.JButton del_Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel level_Label;
    private javax.swing.JSlider level_Slider;
    private javax.swing.JCheckBox touchedT_CB;
    // End of variables declaration//GEN-END:variables

	void trackEvent(EditorEvent e) {
		workingTrack = e.getTrackGroup();
		switch (e.getType()) {
			case EditorEvent.TRACKGROUP_UNSELECTED:
				clone_Button.setEnabled(false);
				del_Button.setEnabled(false);
				clearMark_Button.setEnabled(false);
				break;
			case EditorEvent.TRACKGROUP_SELECTED:
				clone_Button.setEnabled(true);
				del_Button.setEnabled(true);
				clearMark_Button.setEnabled(false);
				break;
			case EditorEvent.TRACKGROUP_AREASELECTED:
				clone_Button.setEnabled(true);
				del_Button.setEnabled(true);
				clearMark_Button.setEnabled(true);
				break;
		}
	}
}
