/*
 * $Revision: 20 $
 * Copyright 2008 js-home.org
 * $Name: not supported by cvs2svn $
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.railsim.gui.panels;

import org.railsim.*;
import org.railsim.editor.EditorActionEvent;
import org.railsim.editor.EditorEvent;
import org.railsim.event.*;
import org.railsim.gui.routesEditor;
import org.railsim.service.path;
import org.railsim.service.trackObjects.pathableObject;

/**
 *
 * @author js
 */
public class mainpanel_editsignal extends javax.swing.JPanel {

	pathableObject currentSignal = null;

	/**
	 * Creates new form mainpanel_file
	 */
	public mainpanel_editsignal() {
		initComponents();
		dataCollector.collector.editorEventListeners.addListener(new AbstractListener() {
			@Override
			public void action(AbstractEvent e) {
				trackEvent((EditorEvent) e);
			}
		});
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        signal_TextField = new javax.swing.JTextField();
        pathdisable_ToggleButton = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        path_ComboBox = new javax.swing.JComboBox();
        manual_Button = new javax.swing.JButton();
        cancel_Button = new javax.swing.JButton();
        openEditorButton = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        signal_TextField.setEditable(false);
        signal_TextField.setPreferredSize(new java.awt.Dimension(80, 20));
        add(signal_TextField);

        pathdisable_ToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/disable path.png")));
        pathdisable_ToggleButton.setText("Signal Fahrstra\u00dfen abschalten");
        pathdisable_ToggleButton.setEnabled(false);
        pathdisable_ToggleButton.setMargin(new java.awt.Insets(2, 5, 2, 5));
        pathdisable_ToggleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pathdisable_ToggleButtonActionPerformed(evt);
            }
        });

        add(pathdisable_ToggleButton);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 20));
        add(jSeparator1);

        path_ComboBox.setEnabled(false);
        path_ComboBox.setPreferredSize(new java.awt.Dimension(90, 22));
        add(path_ComboBox);

        manual_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/setpath.png")));
        manual_Button.setText("Fahrstra\u00dfe manuell");
        manual_Button.setActionCommand("set_path");
        manual_Button.setEnabled(false);
        manual_Button.setMargin(new java.awt.Insets(2, 5, 2, 5));
        add(manual_Button);

        cancel_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/breakpath.png")));
        cancel_Button.setText("anliegende Fahrstra\u00dfe aufheben");
        cancel_Button.setActionCommand("cancel_path");
        cancel_Button.setEnabled(false);
        cancel_Button.setMargin(new java.awt.Insets(2, 5, 2, 5));
        cancel_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonActionPerformed(evt);
            }
        });

        add(cancel_Button);

        openEditorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/routeeditor.png")));
        openEditorButton.setText("Routeneditor...");
        openEditorButton.setMargin(new java.awt.Insets(2, 5, 2, 5));
        openEditorButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openEditorButtonActionPerformed(evt);
            }
        });

        add(openEditorButton);

    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonActionPerformed
    {//GEN-HEADEREND:event_ButtonActionPerformed
		dataCollector.collector.thegame.runAction(new EditorActionEvent(evt));
    }//GEN-LAST:event_ButtonActionPerformed

    private void openEditorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openEditorButtonActionPerformed
    {//GEN-HEADEREND:event_openEditorButtonActionPerformed
		routesEditor.openEditor(this);
    }//GEN-LAST:event_openEditorButtonActionPerformed

    private void pathdisable_ToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pathdisable_ToggleButtonActionPerformed
    {//GEN-HEADEREND:event_pathdisable_ToggleButtonActionPerformed
		if (currentSignal != null) {
			dataCollector.collector.thegame.runAction(new EditorActionEvent<>("enablesignal", !pathdisable_ToggleButton.isSelected()));
		}
    }//GEN-LAST:event_pathdisable_ToggleButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_Button;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton manual_Button;
    private javax.swing.JButton openEditorButton;
    private javax.swing.JComboBox path_ComboBox;
    private javax.swing.JToggleButton pathdisable_ToggleButton;
    private javax.swing.JTextField signal_TextField;
    // End of variables declaration//GEN-END:variables

	void trackEvent(EditorEvent e) {
		switch (e.getType()) {
			case EditorEvent.PATHEDIT_PATHABLE_SELECTED:
				currentSignal = (pathableObject) e.getTrackObject();
				signal_TextField.setText(currentSignal.getName());
				pathdisable_ToggleButton.setEnabled(true);
				pathdisable_ToggleButton.setSelected(!currentSignal.isEnabled());
				manual_Button.setEnabled(true);
				cancel_Button.setEnabled(true);
				path_ComboBox.setEnabled(true);
				updatePathList();
				break;
			case EditorEvent.PATHEDIT_PATHABLE_UNSELECTED:
				currentSignal = null;
				signal_TextField.setText("");
				pathdisable_ToggleButton.setEnabled(false);
				manual_Button.setEnabled(false);
				cancel_Button.setEnabled(false);
				path_ComboBox.setEnabled(false);
				break;
			case EditorEvent.PATHEDIT_PATHABLE_RENAMED:
				break;
			case EditorEvent.PATHEDIT_PATHABLE_STATECHANGED:
				if (currentSignal == e.getTrackObject()) {
					pathdisable_ToggleButton.setSelected(!currentSignal.isEnabled());
				}
				break;
		}
	}

	private void updatePathList() {
		path_ComboBox.removeAllItems();
		if (currentSignal != null) {
			for (path p : currentSignal.getAllPaths()) {
				path_ComboBox.addItem(p);
			}
		}
		if (path_ComboBox.getItemCount() > 0) {
			path_ComboBox.setSelectedIndex(0);
		}
	}
}
