/*
 * $Revision: 18 $
 * Copyright 2008 js-home.org
 * $Name: not supported by cvs2svn $
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.railsim.gui.panels;

import org.railsim.train.timetableEditor;
import org.railsim.train.trainsetEditor;

/**
 *
 * @author js
 */
public class mainpanel_edittrain extends javax.swing.JPanel {

	/**
	 * Creates new form mainpanel_file
	 */
	public mainpanel_edittrain() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        trainsetEditorButton = new javax.swing.JButton();
        trainsrouteButton = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        trainsetEditorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/trainseteditor.png")));
        trainsetEditorButton.setText("Trainset Editor...");
        trainsetEditorButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                trainsetEditorButtonActionPerformed(evt);
            }
        });

        add(trainsetEditorButton);

        trainsrouteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/timetable.png")));
        trainsrouteButton.setText("Timetable Editor...");
        trainsrouteButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                trainsrouteButtonActionPerformed(evt);
            }
        });

        add(trainsrouteButton);

    }// </editor-fold>//GEN-END:initComponents

    private void trainsrouteButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_trainsrouteButtonActionPerformed
    {//GEN-HEADEREND:event_trainsrouteButtonActionPerformed
		timetableEditor.openEditor(this);
    }//GEN-LAST:event_trainsrouteButtonActionPerformed

    private void trainsetEditorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_trainsetEditorButtonActionPerformed
    {//GEN-HEADEREND:event_trainsetEditorButtonActionPerformed
		trainsetEditor.openEditor(this);
    }//GEN-LAST:event_trainsetEditorButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton trainsetEditorButton;
    private javax.swing.JButton trainsrouteButton;
    // End of variables declaration//GEN-END:variables
}
