/*
 * $Revision: 18 $
 * Copyright 2008 js-home.org
 * $Name: not supported by cvs2svn $
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * @author  js
 * @version generated by NetBeans XML module
 */
package org.railsim.train;

import org.railsim.*;
import org.railsim.xml.*;
import org.xml.sax.*;

public class EngineHandlerImpl implements EngineHandler {

	engine currentEngine = null;

	@Override
	public void start_engine(final Attributes meta) throws SAXException {
		currentEngine = new engine(new idtype(meta.getValue("id")), meta.getValue("name"));
	}

	@Override
	public void end_engine() throws SAXException {
		if (currentEngine != null) {
			dataCollector.collector.alltraindata.engines.put(currentEngine.getId(), currentEngine);
			currentEngine = null;
		}
	}

	@Override
	public void handle_power(final Attributes meta) throws SAXException {
		if (currentEngine != null) {
			try {
				currentEngine.setPower(Integer.parseInt(meta.getValue("power")));
				currentEngine.setMaxspeed(Integer.parseInt(meta.getValue("maxspeed")));
				currentEngine.setAcceleration(Float.parseFloat(meta.getValue("acceleration")));
				currentEngine.setDeceleration(Float.parseFloat(meta.getValue("deceleration")));
			} catch (Exception e) {
				dataCollector.collector.gotException(e);
				currentEngine = null;
			}
		}
	}
}
