/*
 * $Revision: 20 $
 * Copyright 2008 js-home.org
 * $Name: not supported by cvs2svn $
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.railsim.gui.panels.readypanels;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import org.railsim.*;
import org.railsim.event.AbstractEvent;
import org.railsim.event.AbstractListener;
import org.railsim.gui.routesEditor;
import org.railsim.service.route;
import org.railsim.service.exceptions.DuplicateEntryException;

/**
 *
 * @author js
 */
public class routesEditorPanel extends javax.swing.JPanel {

	route selectedRoute = null;

	/**
	 * Creates new form routesEditor
	 */
	public routesEditorPanel() {
		initComponents();
		routesList.setModel(new DefaultListModel());
		updateRoutes();
		dataCollector.collector.routeListeners.addListener(new AbstractListener() {
			@Override
			public void action(AbstractEvent e) {
				updateRoutes();
			}
		});
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jScrollPane1 = new javax.swing.JScrollPane();
        routesList = new javax.swing.JList();
        addButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        openEditorButton = new javax.swing.JButton();

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        routesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        routesList.setVisibleRowCount(4);
        routesList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                routesListValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(routesList);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/add.png")));
        addButton.setText("neue Route");
        addButton.setMargin(new java.awt.Insets(1, 2, 1, 2));
        addButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addButtonActionPerformed(evt);
            }
        });

        delButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/delete.png")));
        delButton.setText("l\u00f6sche Route");
        delButton.setEnabled(false);
        delButton.setMargin(new java.awt.Insets(1, 2, 1, 2));
        delButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                delButtonActionPerformed(evt);
            }
        });

        nameTextField.setEnabled(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                nameTextFieldFocusLost(evt);
            }
        });

        openEditorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/railsim/gui/resources/routeeditor.png")));
        openEditorButton.setText("Editor...");
        openEditorButton.setMargin(new java.awt.Insets(1, 2, 1, 2));
        openEditorButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openEditorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openEditorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openEditorButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openEditorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openEditorButtonActionPerformed
    {//GEN-HEADEREND:event_openEditorButtonActionPerformed
		routesEditor.openEditor(this);
    }//GEN-LAST:event_openEditorButtonActionPerformed

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nameTextFieldFocusLost
    {//GEN-HEADEREND:event_nameTextFieldFocusLost
		if (selectedRoute != null) {
			try {
				selectedRoute.setName(nameTextField.getText());
			} catch (DuplicateEntryException ex) {
				JOptionPane.showMessageDialog(this, "Route mit dem Namen " + nameTextField.getText() + "\nexistiert bereits!", "Route existiert!", JOptionPane.ERROR_MESSAGE);
			}
		}
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nameTextFieldActionPerformed
    {//GEN-HEADEREND:event_nameTextFieldActionPerformed
		try {
			selectedRoute.setName(nameTextField.getText());
		} catch (DuplicateEntryException ex) {
			JOptionPane.showMessageDialog(this, "Route mit dem Namen " + nameTextField.getText() + "\nexistiert bereits!", "Route existiert!", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_delButtonActionPerformed
    {//GEN-HEADEREND:event_delButtonActionPerformed
		if (selectedRoute.isUsed()) {
			JOptionPane.showMessageDialog(this, "Route mit dem Namen " + selectedRoute.getName() + "\nwird noch benutzt!", "Route benutzt!", JOptionPane.ERROR_MESSAGE);
		} else {
			selectedRoute.remove();
			selectedRoute = null;
		}
    }//GEN-LAST:event_delButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addButtonActionPerformed
    {//GEN-HEADEREND:event_addButtonActionPerformed
		try {
			route r = new route("neu");
			selectedRoute = r;
		} catch (DuplicateEntryException ex) {
			selectedRoute = route.allroutes.get("neu");
		}
		routesList.setSelectedValue(selectedRoute, true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void routesListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_routesListValueChanged
    {//GEN-HEADEREND:event_routesListValueChanged
		selectedRoute = (route) routesList.getSelectedValue();
		if (selectedRoute != null) {
			delButton.setEnabled(true);
			nameTextField.setEnabled(true);
			nameTextField.setText(selectedRoute.getName());
		} else {
			delButton.setEnabled(false);
			nameTextField.setEnabled(false);
		}
    }//GEN-LAST:event_routesListValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton delButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton openEditorButton;
    private javax.swing.JList routesList;
    // End of variables declaration//GEN-END:variables

	void updateRoutes() {
		DefaultListModel lm = (DefaultListModel) routesList.getModel();
		lm.removeAllElements();
		synchronized (route.allroutes) {
			for (route r : route.allroutes.values()) {
				lm.addElement(r);
			}
		}
		routesList.setSelectedValue(selectedRoute, true);
	}
}
